version: "3.9"

services:
    app:
        build:
            context: .
        env_file:
            - .env
        restart: always
        volumes:
            - static-data:/vol/web
        environment:
            - ALLOWED_HOSTS=django,127.0.0.1,localhost

    nginx:
        build:
            context: ./nginx
        restart: always
        depends_on:
            - app
        ports:
            - 80:8000
            # -80:80
            # - 443:433
        volumes:
            - static-data:/vol/static
            - ./nginx/logs:/var/log/nginx

volumes:
    static-data:
